package com.javaniuniu.generator.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class MemberDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_detail.member_id
     *
     * @mbg.generated
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_detail.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_detail.submission_num
     *
     * @mbg.generated
     */
    private Integer submissionNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_detail.total_checked_num
     *
     * @mbg.generated
     */
    private Integer totalCheckedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_detail.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_detail.member_id
     *
     * @return the value of member_detail.member_id
     *
     * @mbg.generated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_detail.member_id
     *
     * @param memberId the value for member_detail.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_detail.username
     *
     * @return the value of member_detail.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_detail.username
     *
     * @param username the value for member_detail.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_detail.submission_num
     *
     * @return the value of member_detail.submission_num
     *
     * @mbg.generated
     */
    public Integer getSubmissionNum() {
        return submissionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_detail.submission_num
     *
     * @param submissionNum the value for member_detail.submission_num
     *
     * @mbg.generated
     */
    public void setSubmissionNum(Integer submissionNum) {
        this.submissionNum = submissionNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_detail.total_checked_num
     *
     * @return the value of member_detail.total_checked_num
     *
     * @mbg.generated
     */
    public Integer getTotalCheckedNum() {
        return totalCheckedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_detail.total_checked_num
     *
     * @param totalCheckedNum the value for member_detail.total_checked_num
     *
     * @mbg.generated
     */
    public void setTotalCheckedNum(Integer totalCheckedNum) {
        this.totalCheckedNum = totalCheckedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_detail.status
     *
     * @return the value of member_detail.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_detail.status
     *
     * @param status the value for member_detail.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", memberId=").append(memberId);
        sb.append(", username=").append(username);
        sb.append(", submissionNum=").append(submissionNum);
        sb.append(", totalCheckedNum=").append(totalCheckedNum);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MemberDetail other = (MemberDetail) that;
        return (this.getMemberId() == null ? other.getMemberId() == null : this.getMemberId().equals(other.getMemberId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getSubmissionNum() == null ? other.getSubmissionNum() == null : this.getSubmissionNum().equals(other.getSubmissionNum()))
            && (this.getTotalCheckedNum() == null ? other.getTotalCheckedNum() == null : this.getTotalCheckedNum().equals(other.getTotalCheckedNum()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getMemberId() == null) ? 0 : getMemberId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getSubmissionNum() == null) ? 0 : getSubmissionNum().hashCode());
        result = prime * result + ((getTotalCheckedNum() == null) ? 0 : getTotalCheckedNum().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    public enum Column {
        memberId("member_id", "memberId", "INTEGER", false),
        username("username", "username", "VARCHAR", false),
        submissionNum("submission_num", "submissionNum", "INTEGER", false),
        totalCheckedNum("total_checked_num", "totalCheckedNum", "INTEGER", false),
        status("status", "status", "INTEGER", true);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table member_detail
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}