package com.javaniuniu.generator.domain;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;

public class Problem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_id
     *
     * @mbg.generated
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_index
     *
     * @mbg.generated
     */
    private Integer problemIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.problem_date
     *
     * @mbg.generated
     */
    private LocalDate problemDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.cn_name
     *
     * @mbg.generated
     */
    private String cnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.en_name
     *
     * @mbg.generated
     */
    private String enName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.cn_title
     *
     * @mbg.generated
     */
    private String cnTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column problem.en_title
     *
     * @mbg.generated
     */
    private String enTitle;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_id
     *
     * @return the value of problem.problem_id
     *
     * @mbg.generated
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_id
     *
     * @param problemId the value for problem.problem_id
     *
     * @mbg.generated
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_index
     *
     * @return the value of problem.problem_index
     *
     * @mbg.generated
     */
    public Integer getProblemIndex() {
        return problemIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_index
     *
     * @param problemIndex the value for problem.problem_index
     *
     * @mbg.generated
     */
    public void setProblemIndex(Integer problemIndex) {
        this.problemIndex = problemIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.problem_date
     *
     * @return the value of problem.problem_date
     *
     * @mbg.generated
     */
    public LocalDate getProblemDate() {
        return problemDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.problem_date
     *
     * @param problemDate the value for problem.problem_date
     *
     * @mbg.generated
     */
    public void setProblemDate(LocalDate problemDate) {
        this.problemDate = problemDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.cn_name
     *
     * @return the value of problem.cn_name
     *
     * @mbg.generated
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.cn_name
     *
     * @param cnName the value for problem.cn_name
     *
     * @mbg.generated
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.en_name
     *
     * @return the value of problem.en_name
     *
     * @mbg.generated
     */
    public String getEnName() {
        return enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.en_name
     *
     * @param enName the value for problem.en_name
     *
     * @mbg.generated
     */
    public void setEnName(String enName) {
        this.enName = enName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.cn_title
     *
     * @return the value of problem.cn_title
     *
     * @mbg.generated
     */
    public String getCnTitle() {
        return cnTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.cn_title
     *
     * @param cnTitle the value for problem.cn_title
     *
     * @mbg.generated
     */
    public void setCnTitle(String cnTitle) {
        this.cnTitle = cnTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column problem.en_title
     *
     * @return the value of problem.en_title
     *
     * @mbg.generated
     */
    public String getEnTitle() {
        return enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column problem.en_title
     *
     * @param enTitle the value for problem.en_title
     *
     * @mbg.generated
     */
    public void setEnTitle(String enTitle) {
        this.enTitle = enTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", problemId=").append(problemId);
        sb.append(", problemIndex=").append(problemIndex);
        sb.append(", problemDate=").append(problemDate);
        sb.append(", cnName=").append(cnName);
        sb.append(", enName=").append(enName);
        sb.append(", cnTitle=").append(cnTitle);
        sb.append(", enTitle=").append(enTitle);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Problem other = (Problem) that;
        return (this.getProblemId() == null ? other.getProblemId() == null : this.getProblemId().equals(other.getProblemId()))
            && (this.getProblemIndex() == null ? other.getProblemIndex() == null : this.getProblemIndex().equals(other.getProblemIndex()))
            && (this.getProblemDate() == null ? other.getProblemDate() == null : this.getProblemDate().equals(other.getProblemDate()))
            && (this.getCnName() == null ? other.getCnName() == null : this.getCnName().equals(other.getCnName()))
            && (this.getEnName() == null ? other.getEnName() == null : this.getEnName().equals(other.getEnName()))
            && (this.getCnTitle() == null ? other.getCnTitle() == null : this.getCnTitle().equals(other.getCnTitle()))
            && (this.getEnTitle() == null ? other.getEnTitle() == null : this.getEnTitle().equals(other.getEnTitle()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table problem
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProblemId() == null) ? 0 : getProblemId().hashCode());
        result = prime * result + ((getProblemIndex() == null) ? 0 : getProblemIndex().hashCode());
        result = prime * result + ((getProblemDate() == null) ? 0 : getProblemDate().hashCode());
        result = prime * result + ((getCnName() == null) ? 0 : getCnName().hashCode());
        result = prime * result + ((getEnName() == null) ? 0 : getEnName().hashCode());
        result = prime * result + ((getCnTitle() == null) ? 0 : getCnTitle().hashCode());
        result = prime * result + ((getEnTitle() == null) ? 0 : getEnTitle().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table problem
     *
     * @mbg.generated
     */
    public enum Column {
        problemId("problem_id", "problemId", "INTEGER", false),
        problemIndex("problem_index", "problemIndex", "INTEGER", false),
        problemDate("problem_date", "problemDate", "DATE", false),
        cnName("cn_name", "cnName", "VARCHAR", false),
        enName("en_name", "enName", "VARCHAR", false),
        cnTitle("cn_title", "cnTitle", "VARCHAR", false),
        enTitle("en_title", "enTitle", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table problem
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public static Column[] all() {
            return Column.values();
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table problem
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}