package com.javaniuniu.generator.mapper;

import com.javaniuniu.generator.domain.InfoDetail;
import com.javaniuniu.generator.domain.example.InfoDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    long countByExample(InfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    int deleteByExample(InfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    int insert(InfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    int insertSelective(InfoDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    InfoDetail selectOneByExample(InfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    InfoDetail selectOneByExampleSelective(@Param("example") InfoDetailExample example, @Param("selective") InfoDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    List<InfoDetail> selectByExampleSelective(@Param("example") InfoDetailExample example, @Param("selective") InfoDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    List<InfoDetail> selectByExample(InfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") InfoDetail record, @Param("example") InfoDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") InfoDetail record, @Param("example") InfoDetailExample example);
}