package com.javaniuniu.generator.mapper;

import com.javaniuniu.generator.domain.MemberDetail;
import com.javaniuniu.generator.domain.example.MemberDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    long countByExample(MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int deleteByExample(MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int insert(MemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int insertSelective(MemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    MemberDetail selectOneByExample(MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    MemberDetail selectOneByExampleSelective(@Param("example") MemberDetailExample example, @Param("selective") MemberDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    List<MemberDetail> selectByExampleSelective(@Param("example") MemberDetailExample example, @Param("selective") MemberDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    List<MemberDetail> selectByExample(MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    MemberDetail selectByPrimaryKeySelective(@Param("memberId") Integer memberId, @Param("selective") MemberDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    MemberDetail selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberDetail record, @Param("example") MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberDetail record, @Param("example") MemberDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberDetail record);
}